import { MagazineData } from '../types';
import heroCoverImg from '../assets/images/hero_monsoon_cover_1790928584095.jpg';
import storyLastDanceImg from '../assets/images/story_last_dance_1790928636006.jpg';
import storyCloudsGatherImg from '../assets/images/story_clouds_gather_1790928596438.jpg';
import storyBeyondNetImg from '../assets/images/story_beyond_net_1790928618698.jpg';
import storyDownpourImg from '../assets/images/story_downpour_1790928667585.jpg';
import storyRainGlassImg from '../assets/images/story_rain_glass_1790928607247.jpg';
import storyPausePerceiveImg from '../assets/images/story_pause_perceive_1790928650572.jpg';

export const INITIAL_MAGAZINE_DATA: MagazineData = {
  siteInfo: {
    magazineName: "PARALLEL PERSPECTIVES",
    issueNumber: "Issue 01",
    theme: "Monsoon",
    publishedFrequency: "Published Quarterly",
    instagramHandle: "@parallelperspectives295",
    instagramUrl: "https://instagram.com/parallelperspectives295",
    email: "parallelperspectives529@gmail.com",
    headerCtaText: "Read Issue 01",
    navLinks: [
      { id: '1', label: 'Issue 01: Monsoon', target: 'hero' },
      { id: '2', label: "Founders' Note", target: 'founders-note' },
      { id: '3', label: 'Featured Stories', target: 'featured-stories' },
      { id: '4', label: 'Flipbook', target: 'flipbook' },
      { id: '5', label: 'Submissions', target: 'submissions' },
    ],
    logo: {
      prefix: "PARA",
      suffix: "EL",
      subtitle: "PERSPECTIVES",
      showPillars: true,
      customImageUrl: "",
      scale: 1.0,
      offsetX: 0,
      offsetY: 0,
      placements: {
        header: true,
        hero: true,
        footer: true,
      },
    },
  },
  hero: {
    badge: "Issue 01 — Theme: Monsoon | Published Quarterly",
    title: "PARALLEL PERSPECTIVES",
    subtitle: "A Quarterly Fine-Art Photography Publication",
    excerpt: "For our very first issue, we chose Monsoon because it's a season that quietly transforms the world around us. Familiar streets become mirrors, raindrops create patterns we often overlook, and ordinary places feel alive.",
    curatorsPrefix: "Curation:",
    curators: "Founded & Curated by Dev Pedhadia & Khushal Nasit",
    details: "16 Pages · Fine Art Photography · Limited Print & Digital Release",
    coverImage: heroCoverImg,
    ctaFlipbookText: "Open Flipbook",
    ctaStoriesText: "Explore Stories",
  },
  quote: {
    categoryTag: "Editorial Philosophy",
    text: "You don't take a photograph, you make it.",
    author: "Ansel Adams",
    citation: "Featured in Issue 01: Monsoon Editorial Prologue",
  },
  foundersStory: {
    tag: "Letter from the Perspectives",
    title: "Two Lenses, One Atmosphere: The School Bus Genesis",
    subtitle: "How a daily school bus ride transformed into an ongoing dialog through viewfinders.",
    p1: "It started with a casual conversation on the morning school bus between Dev Pedhadia and Khushal Nasit. What began as discussions about camera lenses, shutter clicks, and framing soon turned into shared weekend photo walks across the city — exploring the quiet symmetry of architecture and the untamed beauty of natural weather.",
    p2: "We soon noticed an intriguing dynamic: standing side-by-side in the exact same spot, looking at the exact same subject, our resulting frames captured completely different truths. One leaned into brutalist geometry, structural tension, and sharp lines; the other searched for fleeting reflections, emotional cadence, and atmospheric breathing room.",
    p3: "Parallel Perspectives was born from this exact revelation: two distinct creative viewpoints running side by side, intersecting only in their dedication to visual honesty. For our debut issue, Monsoon, we invite you to experience how rain washes away visual noise, revealing the poetry hidden in everyday moments.",
    curatorsSectionTag: "The Curators Behind the Pages",
    curatorsSectionTitle: "Dev Pedhadia & Khushal Nasit",
    founder1Name: "Dev Pedhadia",
    founder1Role: "Co-Founder & Visual Editor",
    founder1Tag: "01 / Curatorial",
    founder1Bio: "Focused on high-contrast architectural street frames, geometry, and finding visual tension in everyday urban rhythms.",
    founder2Name: "Khushal Nasit",
    founder2Role: "Co-Founder & Creative Director",
    founder2Tag: "02 / Creative",
    founder2Bio: "Drawn to atmospheric gradients, fleeting weather phenomena, and macro reflections that turn rain puddles into liquid portals.",
    noteSignoff: "Captured with intention. Printed with care.",
    foundedLabel: "Founded",
    foundedValue: "2026 · Quarterly",
    mediumLabel: "Print Medium",
    mediumValue: "Fine Art Photography",
  },
  featuredSection: {
    tag: "Editorial Selection",
    title: "Featured Perspectives",
    description: "Six pivotal visual essays from the debut Monsoon print edition. Click any photograph to inspect high-resolution plates and technical notes.",
  },
  stories: [
    {
      id: "1",
      title: "The Last Dance",
      teaser: "One final performance before the rain takes over.",
      photographer: "Dev Pedhadia",
      tag: "Street Rhythm · Monsoon Prelude",
      exif: "35mm · ƒ/1.8 · 1/500s · ISO 100",
      image: storyLastDanceImg,
      storyBody: "An empty asphalt court on the verge of rain. Wind whips through the trees as dark clouds roll in. A lone figure moves across the frame — an instinctive, fleeting gesture captured in fine-art print.",
    },
    {
      id: "2",
      title: "As The Clouds Gather",
      teaser: "A subtle shift in light and shadow, capturing the quiet calm that follows the storm.",
      photographer: "Dev Pedhadia",
      tag: "Atmospheric Horizon",
      exif: "50mm · ƒ/2.8 · 1/250s · ISO 200",
      image: storyCloudsGatherImg,
      storyBody: "The sky drops low over the skyline. Natural diffusion softens every harsh urban edge into charcoal gradients. Rain is seconds away.",
    },
    {
      id: "3",
      title: "Beyond The Net",
      teaser: "A quiet moment before the sky tells its story.",
      photographer: "Khushal Nasit",
      tag: "Geometry · Texture",
      exif: "28mm · ƒ/4.0 · 1/125s · ISO 400",
      image: storyBeyondNetImg,
      storyBody: "Looking through water droplets clinging to wire barriers reveals microscopic refractive lenses. We explore how restriction itself frames unexpected beauty.",
    },
    {
      id: "4",
      title: "Before The Downpour",
      teaser: "The heavy silence right before rain drops meet asphalt.",
      photographer: "Dev Pedhadia",
      tag: "Urban Landscape",
      exif: "24mm · ƒ/5.6 · 1/400s · ISO 100",
      image: storyDownpourImg,
      storyBody: "Pedestrians quicken their pace; street stalls pull out plastic tarps. The architecture stands stark and silent under the brooding monsoon ceiling.",
    },
    {
      id: "5",
      title: "Through Rain-Stained Glass",
      teaser: "When raindrops turn ordinary windows into art.",
      photographer: "Dev Pedhadia",
      tag: "Abstraction · Reflection",
      exif: "85mm · ƒ/2.0 · 1/200s · ISO 800",
      image: storyRainGlassImg,
      storyBody: "Interior warmth meets exterior dampness. Condensed droplets transform a banal transit window into an impressionist canvas of refracted streetlamps and blurred neon signs.",
    },
    {
      id: "6",
      title: "Pause & Perceive",
      teaser: "Slow down — there's always more than meets the eye.",
      photographer: "Khushal Nasit",
      tag: "Minimalism · Puddle Mirror",
      exif: "35mm · ƒ/4.0 · 1/160s · ISO 160",
      image: storyPausePerceiveImg,
      storyBody: "An asphalt depression collects rain and turns into an upside-down city. Most rush past trying not to step in it; we crouched low with our viewfinders to discover another world.",
    },
  ],
  flipbook: {
    tag: "Issue 01 Digital Edition",
    title: "Issue 01: Monsoon — Digital Flipbook",
    subtitle: "Complete 16-Page Editorial Edition",
    description: "Experience the complete 16-page fine-art publication in high definition on Heyzine with authentic page-turn acoustics, dual-page fine art spreads, and tactile typography.",
    embedUrl: "https://heyzine.com",
    heyzineUrl: "https://heyzine.com",
    buttonText: "Read Issue 01 on Heyzine",
    badgeText: "Hosted on Heyzine",
    metaDetails: "16 Archival Pages · Fine Art Spreads · High-Resolution Flipbook",
    totalPages: 16,
    colophon: "Curated in Ahmedabad & Mumbai · Limited Print Circulation",
  },
  issue02: {
    badge: "Next Quarterly Edition",
    title: "Issue 02 — Guess the theme for the next issue?",
    description: "As Monsoon concludes its circulation, Dev and Khushal are curating the second installment. Can you decipher the single-word theme before the official editorial announcement?",
    pollPrompt: "Complete the Word — Fill in the Blanks:",
    targetWord: "SHADOWS",
    clue: "Clue: The interplay of intense architectural contrast that defines the golden hour.",
    revealedIndices: [0, 4],
    successMessage: "Brilliant perspective! You uncovered the theme for Issue 02: SHADOWS.",
  },
  submission: {
    tag: "Open Call for Lens Artists",
    title: "Submit Your Perspective",
    subtitle: "We believe visionary photography happens everywhere — not just in studios. We invite submissions for Issue 02 and digital features.",
    guidelinesTitle: "Curatorial Guidelines",
    guidelines: "We evaluate series of 5 to 10 cohesive frames. Prioritize honesty, contrast, and distinct point-of-view over sterile perfection. Both digital and film formats are welcomed.",
    directInquiryPrefix: "Direct inquiries:",
    instagramPrefix: "Instagram:",
  },
  footer: {
    newsletterTitle: "Join the Perspective — Quarterly Releases",
    newsletterDesc: "Subscribers receive priority digital access, print batch notifications, and behind-the-lens essays directly from Dev & Khushal.",
    directoryHeading: "Directory",
    connectHeading: "Connect With Us",
    returnToTopText: "Return to Top",
    footerTagline: "Quarterly Photography Journal · Issue 01 Monsoon",
    address: "Independent Quarterly Photography Journal · Curated in Mumbai & Ahmedabad · Global Distribution",
    editorialManifesto: "Parallel Perspectives is an independent quarterly publication committed to authentic observational photography, slow editorial craft, and celebrating the duality of human vision.",
    copyright: "© 2026 Parallel Perspectives. Founded by Dev Pedhadia & Khushal Nasit. All rights reserved. Photographs remain the intellectual property of their original creators.",
  },
};
